// icons.module.ts
import { NgModule } from '@angular/core';
import { NgIconsModule } from '@ng-icons/core';
import {ionHomeOutline,ionRocketOutline,ionBriefcase,ionPeople,ionPaperPlane,ionLogInOutline,ionMenuOutline,ionCloseOutline,ionLogoGoogle,ionEye,ionEyeOff,ionPersonOutline,ionDocument,ionAddCircle,ionDocumentTextOutline,ionFileTrayFullOutline,ionPersonCircleOutline,ionBriefcaseOutline,ionNotificationsOutline,ionRocket,ionDocuments,ionPerson,ionNotifications,ionJournal,ionLocationOutline,ionCashOutline,ionCalendarOutline,ionMail,ionSave,ionStatsChart,ionCalendar, ionLocation, ionStar, ionStarHalf, ionTimeOutline, ionClose, ionRefresh, ionAdd, ionSearch, ionSpeedometer, ionHardwareChip, ionSparkles, ionShieldCheckmark, ionBusinessOutline, ionHammer, ionMailOpen, ionDocumentText, ionTime, ionPencil, ionTrash, ionArrowUp, ionArrowDown, ionFlash, ionTrendingUp, ionShield, ionCreate, ionGlobe, ionInformationCircle, ionWarning, ionAlert, ionAlertCircle, ionGitMerge, ionRefreshCircle, ionCheckmarkCircle, ionRibbon, ionCloudDownload, ionLockClosed, ionCheckmark, ionScan, ionKey, ionEllipsisVertical, ionDocumentLock, ionSync, ionSyncOutline, ionVideocam, ionSadOutline, ionAddOutline, ionPersonCircle, } from '@ng-icons/ionicons';

@NgModule({
  imports: [NgIconsModule.withIcons({ionHomeOutline,ionRocketOutline,ionBriefcase,ionPeople,ionPaperPlane,ionLogInOutline,ionMenuOutline,ionCloseOutline,ionLogoGoogle,ionEye,ionEyeOff,ionPersonOutline,ionDocument,ionAddCircle,ionDocumentTextOutline,ionFileTrayFullOutline,ionPersonCircleOutline,ionBriefcaseOutline,ionNotificationsOutline,ionRocket,ionDocuments,ionPerson,ionNotifications,ionJournal,ionLocationOutline,ionCashOutline,ionCalendarOutline,ionMail,ionSave,ionStatsChart,ionCalendar,ionLocation,ionStar,ionStarHalf,ionTimeOutline,ionClose,ionRefresh,ionAdd,ionSearch,ionSpeedometer,ionHardwareChip,ionSparkles,ionShieldCheckmark,ionBusinessOutline,ionHammer,ionMailOpen,ionDocumentText,ionTime,ionPencil,ionTrash,ionArrowUp,ionArrowDown,ionFlash,ionTrendingUp,ionShield,ionCreate,ionGlobe,ionInformationCircle,ionWarning,ionAlertCircle,ionGitMerge,ionRefreshCircle,ionCheckmarkCircle,ionRibbon,ionCloudDownload,ionLockClosed,ionCheckmark,ionScan,ionKey,ionDocumentLock,ionEllipsisVertical ,ionSync,ionSyncOutline,ionVideocam,ionSadOutline,ionAddOutline,ionPersonCircle  })],
  exports: [NgIconsModule]
})
export class IconsModule {}
